### ISSUE TITLE
You cannot use the Aerial screen saver with this version of OS X

### ISSUE THREAD

**Issue by esetnik** [esetnik/Aerial#1]
Continuation of discussion regarding bundling of swift 3 libs https://github.com/JohnCoates/Aerial/issues/378

**Comment by esetnik** [comment]
I am using `SWIFT_VERSION = 3.0;` and still have the same issue. https://github.com/JohnCoates/Aerial/compare/master...esetnik:feature/4k?expand=1#diff-e23dd4f46f78295fd69cd5f93bf41f9bR601

**Comment by Gelioks** [comment]
Thanks, @esetnik, the instruction you've posted in [JohnCoates#378](https://github.com/JohnCoates/Aerial/issues/378#issuecomment-346442784) has resolved the issue.

**Comment by tweichart** [comment]
downloaded the latestst release + deleted old files, still no way to actually activate it via screensaver settings, error is displayed like described in the headline in the small preview box on the right...

**Comment by esetnik** [comment]
Are you compiling from source or downloading the zipped release? If you compile from source you have to use Xcode 8. If you are downloading the zipped release I already compiled it with Xcode 8 so it should "Just Work™". But you will still need to follow instructions at https://github.com/JohnCoates/Aerial/issues/4 if you are having issues.

It should be sufficient to select Aerial as your screen saver and quit and reopen System Preferences.

**Comment by tweichart** [comment]
oh ok, it just showed the error in the preview window. after ignoring it, quitting and reopening it now works. thanks so much 👍

**Comment by esetnik** [comment]
Happy to help
