### ISSUE TITLE
Video stutter and immediately high fan 

### ISSUE THREAD

**Issue by DJay-X** [esetnik/Aerial#2]
First, thanks @esetnik for the ongoing development on Aerial.
Installed yesterday I noticed that the screensaver videos stutters here and the fan is going high immediately because of cpu usage.

macOS 10.13.2 Beta (17C79a) iMac (21.5-inch, Late 2012), 3,1 GHz Intel Core i7, 16 GB 1600 MHz DDR3, 1,12 TB Fusion Drive.

![bildschirmfoto 2017-11-23 um 16 19 02](https://user-images.githubusercontent.com/3874239/33179549-146cff24-d06a-11e7-95dd-bc25cbadbb14.png)

**Comment by esetnik** [comment]
You are probably on the edge of acceptable hardware for 4K video decoding. Can you download this file directly https://sylvan.apple.com/Aerials/2x/Videos/DB_D011_C009_4K_SDR_HEVC.mov and play it in QuickTime without similar issues?

**Comment by DJay-X** [comment]
Oh wow. Thx.
I now feel a little bit embarrassed. 😊
Your were right. Just running the video in QuickTime also shoots CPU high and fan on. 😔
I think this is the time to realize that my iMac is old and officially out dated. 😩

Sorry for bothering and thanks again for your reply.
