### ISSUE TITLE
Fans kick in after starting the screensaver

### ISSUE THREAD

**Issue by sbashwin** [esetnik/Aerial#3]
I have been using this for last 3/4 days. I have noticed after the screen saver starts, after few mins. My MacBook Pro 15" 2015 fans start spinning at high speeds. Is this a known issue??

**Comment by esetnik** [comment]
This is probably the same issue as #2. The MacBook Pro has a weak GPU and bad airflow so it’s liable to get hot quickly. My 2016 MBP runs full fans all the time when connected to two external 4K monitors even when I’m not doing anything on the system. Follow the test instructions in #2 to confirm that video decoding is the cause of your excessive heat. If it’s a problem for you you could try the official Aerial which only supports 1080p videos and won’t cause as much heat on your system.

**Comment by sbashwin** [comment]
Thanks so much for replying!

Yes, you are right! By just playing a 4k video for a minute or two. The fans are at high speeds. Which is the official app? The one I downloaded was from your repository.

**Comment by esetnik** [comment]
The official / original is https://github.com/JohnCoates/Aerial
