### ISSUE TITLE
Heavy CPU/GPU usage on 2016 MBP when Plugged into External Monitors

### ISSUE THREAD

**Issue by huebs** [esetnik/Aerial#4]
As mentioned in JohnCoates/Aerial#378, when I plug my laptop into two 2560x1440 displays. It will only use the discrete GPU when external monitors are connected. I get the same results when I plug it into my 4K TV @ 60Hz.

```
Model:     2016 MacBook Pro
Processor: 2.9GHz Core i7
Memory:    16 GB
Graphics:  Radeon Pro 460
```

**Comment by esetnik** [comment]
See #2, #3 for instructions on verifying that this is related to GPU decoding performance in High Sierra and not directly related to Aerial.
