### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by narin** [esetnik/Aerial#5]
Could not get this to work on my 2017 MacBook Pro 13" or my Hackintosh.  Both produce a black screen and no video play.

**Comment by esetnik** [comment]
Do you see the Aerial screensaver preview in System Preferences?

**Comment by narin** [comment]
Yes.  Also when I go into the settings, I see this:

https://screencast.com/t/gxnCFhfBEamA

**Comment by esetnik** [comment]
I have not encountered that before. Can you confirm that you can play the cached HEVC videos in QuickTime. To test, try downloading https://sylvan.apple.com/Aerials/2x/Videos/DB_D011_C009_4K_SDR_HEVC.mov and playing it in QuickTime.
